export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const FILTER_ARTICLELIST_BY_DATE = 'FILTER_ARTICLELIST_BY_DATE'

export const FILTER_ARTICLELIST_BY_ITEMS = 'FILTER_ARTICLELIST_BY_ITEMS'